const startAdmin = () => { if (!window.supabase || !window.TINGS_SUPABASE) return setTimeout(startAdmin, 50); const db = window.supabase.createClient(TINGS_SUPABASE.url,TINGS_SUPABASE.anonKey); const OWNER_EMAIL='chenghanchen1@gmail.com', $=s=>document.querySelector(s), money=n=>`$${Number(n).toFixed(2)}`;
function toast(m){$('#toast').textContent=m;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2800)}
async function data(table){const {data,error}=await db.from(table).select('*').order(table==='orders'?'created_at':'id',{ascending:false});if(error)toast(error.message);return data||[]}
async function orders(){const o=await data('orders'),today=new Date().toLocaleDateString('zh-CN');$('#allOrders').textContent=o.length;$('#newOrders').textContent=o.filter(x=>x.status==='新订单').length;$('#orderBadge').textContent=o.filter(x=>x.status==='新订单').length;$('#todayAmount').textContent=money(o.filter(x=>new Date(x.created_at).toLocaleDateString('zh-CN')===today).reduce((s,x)=>s+Number(x.subtotal),0));$('#ordersList').innerHTML=o.length?o.map(x=>`<article class="order-card"><div class="order-top"><div><h3>${x.order_number} · ${x.customer_name}</h3><p class="order-meta">${x.phone}${x.email?` · ${x.email}`:''} · ${new Date(x.created_at).toLocaleString()}</p></div><span class="status ${x.status==='已确认'?'done':''}">${x.status}</span></div><p class="order-items">${x.items.map(i=>`${i.name} × ${i.qty}`).join('、')}</p><div class="order-actions"><span class="order-meta">${x.fulfillment==='delivery'?`配送：${x.address}`:'到店自取'} · ${money(x.subtotal)}</span><button data-confirm="${x.id}">${x.status==='新订单'?'标记为已确认':'已确认'}</button></div></article>`).join(''):'<p class="muted">还没有订单。</p>';}
async function products(){const p=await data('products');$('#productsList').innerHTML=p.map(x=>`<article class="product-row"><div class="product-thumb" style="background:${x.color}">${x.image?`<img src="${x.image}" alt="">`:x.icon}</div><div><h3>${x.name}</h3><p>${x.note}</p></div><span>${x.type}</span><b>${money(x.price)}</b><button data-edit="${x.id}">编辑</button></article>`).join('');}
async function categories(){const c=await data('categories');$('#categoryList').innerHTML=c.map(x=>`<span>${x.name}<button data-category="${x.id}">×</button></span>`).join('');return c}
const contentDefaults={heroEyebrow:'今日の小さなごほうび',heroTitle:'把喜欢的零食，',heroEmphasis:'装进日常里。',heroIntro:'从童年味道到新鲜人气款，挑一袋让心情变好的中国零食。下单即为您预留，无需在线付款。',heroButton:'开始挑选',heroCardOneIcon:'米',heroCardOneText:'锅巴',heroCardTwoIcon:'桃',heroCardTwoText:'果干',heroBadgeTop:'おやつ',heroBadgeBottom:'TIME',storyMark:'小町',storyEyebrow:'About Komachi',storyTitle:'一间认真挑选',storySubtitle:'小快乐的零食屋',storyText:'我们相信，零食是平凡日子里的小仪式感。每一件上架的商品，都希望让你想起某个温暖的下午。',storySignature:'おいしい時間を、どうぞ。',footerHours:'营业时间：每日 10:00 – 21:00',footerYear:'2026'};
async function settings(){const {data:s}=await db.from('shop_settings').select('*').eq('id',1).single();if(s){$('#shopName').value=s.name;$('#shopEnglish').value=s.english;$('#deliveryText').value=s.delivery;const content={...contentDefaults,...(s.content||{})};Object.entries(content).forEach(([key,value])=>{const input=$(`#${key}Input`);if(input)input.value=value;});}}
async function openProduct(p){const c=await categories();$('#productDialogTitle').textContent=p?'编辑商品':'添加商品';$('#productId').value=p?.id||'';$('#productName').value=p?.name||'';$('#productNote').value=p?.note||'';$('#productPrice').value=p?.price||'';$('#productIcon').value=p?.icon||'🍪';$('#productColor').value=p?.color||'#e5c68d';$('#productType').innerHTML=c.map(x=>`<option ${x.name===p?.type?'selected':''}>${x.name}</option>`).join('');$('#imagePreview').innerHTML=p?.image?`<img src="${p.image}">`:p?.icon||'🍪';$('#productImage').value='';$('#productDialog').dataset.image=p?.image||'';$('#productDialog').showModal();}
function login(){document.querySelector('aside').style.display='none';$('main').innerHTML=`<header><div><p class="eyebrow">OWNER ACCESS</p><h1>店主登录</h1></div></header><section class="panel narrow"><p class="muted">仅店主账号可查看订单和管理网站。</p><form id="loginForm"><label>店主邮箱<input id="loginEmail" type="email" value="${OWNER_EMAIL}" required autocomplete="email"></label><label>密码<input id="loginPassword" type="password" required autocomplete="current-password"></label><button class="primary">登录后台</button><button class="text-btn" type="button" id="resetPassword">设置／忘记密码</button></form></section>`;$('#loginForm').onsubmit=async e=>{e.preventDefault();const {data,error}=await db.auth.signInWithPassword({email:$('#loginEmail').value,password:$('#loginPassword').value});if(error)return toast('邮箱或密码不正确');if(data.user?.email!==OWNER_EMAIL){await db.auth.signOut();return toast('此账号没有店主权限');}location.reload();};$('#resetPassword').onclick=async()=>{const {error}=await db.auth.resetPasswordForEmail($('#loginEmail').value,{redirectTo:location.href.split('#')[0]});toast(error?error.message:'密码设置链接已发送到邮箱，请在同一设备打开。');};}
function resetPassword(){document.querySelector('aside').style.display='none';$('main').innerHTML=`<header><div><p class="eyebrow">OWNER ACCESS</p><h1>设置新密码</h1></div></header><section class="panel narrow"><form id="newPasswordForm"><label>新密码<input id="newPassword" type="password" minlength="8" required autocomplete="new-password"></label><label>再次输入新密码<input id="confirmPassword" type="password" minlength="8" required autocomplete="new-password"></label><button class="primary">保存新密码</button></form></section>`;$('#newPasswordForm').onsubmit=async e=>{e.preventDefault();if($('#newPassword').value!==$('#confirmPassword').value)return toast('两次输入的密码不一致');const {error}=await db.auth.updateUser({password:$('#newPassword').value});if(error)return toast(error.message);history.replaceState({},'',location.pathname);toast('密码已设置，请重新登录');await db.auth.signOut();setTimeout(()=>location.reload(),900);};}
async function boot(){await Promise.all([orders(),products(),categories(),settings()]);db.channel('order-alert').on('postgres_changes',{event:'INSERT',schema:'public',table:'orders'},p=>{toast('收到一笔新订单！');orders();}).on('postgres_changes',{event:'*',schema:'public',table:'products'},products).on('postgres_changes',{event:'*',schema:'public',table:'categories'},categories).on('postgres_changes',{event:'*',schema:'public',table:'shop_settings'},settings).subscribe();}
document.querySelectorAll('aside nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('aside nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}`).classList.add('active');$('#pageTitle').textContent=b.textContent.replace(/\d+/g,'').trim();});
$('#ordersList').onclick=async e=>{if(e.target.dataset.confirm){await db.from('orders').update({status:'已确认'}).eq('id',e.target.dataset.confirm);orders();}};$('#newProduct').onclick=()=>openProduct();$('#closeProduct').onclick=()=>$('#productDialog').close();$('#productsList').onclick=async e=>{if(e.target.dataset.edit){const {data:p}=await db.from('products').select('*').eq('id',e.target.dataset.edit).single();openProduct(p);}};
$('#productImage').onchange=e=>{const r=new FileReader();if(e.target.files[0]){r.onload=()=>{$('#productDialog').dataset.image=r.result;$('#imagePreview').innerHTML=`<img src="${r.result}">`;};r.readAsDataURL(e.target.files[0]);}};
$('#productForm').onsubmit=async e=>{e.preventDefault();const id=$('#productId').value||Date.now(),row={id:+id,name:$('#productName').value,note:$('#productNote').value,type:$('#productType').value,price:+$('#productPrice').value,icon:$('#productIcon').value,color:$('#productColor').value,image:$('#productDialog').dataset.image||null,is_active:true,updated_at:new Date().toISOString()};const {error}=await db.from('products').upsert(row);if(error)return toast(error.message);$('#productDialog').close();toast('商品已保存');products();};
$('#categoryForm').onsubmit=async e=>{e.preventDefault();const {error}=await db.from('categories').insert({name:$('#categoryName').value.trim()});if(error)return toast(error.message);$('#categoryName').value='';categories();};$('#categoryList').onclick=async e=>{if(e.target.dataset.category){const {error}=await db.from('categories').delete().eq('id',e.target.dataset.category);toast(error?error.message:'分类已删除');categories();}};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const content={};Object.keys(contentDefaults).forEach(key=>content[key]=$(`#${key}Input`).value.trim()||contentDefaults[key]);const {error}=await db.from('shop_settings').update({name:$('#shopName').value,english:$('#shopEnglish').value,delivery:$('#deliveryText').value,content,updated_at:new Date().toISOString()}).eq('id',1);toast(error?error.message:'网页内容已保存');};(async()=>{if(location.hash.includes('type=recovery'))return resetPassword();const {data:{session}}=await db.auth.getSession();if(session?.user?.email===OWNER_EMAIL)return boot();if(session)await db.auth.signOut();login();})();};startAdmin();
