const db = window.supabase.createClient(TINGS_SUPABASE.url, TINGS_SUPABASE.anonKey);
let products = [], categories = [], cart = [];
const $ = s => document.querySelector(s), dollars = n => `$${Number(n).toFixed(2)}`, escapeHtml = v => String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderFilters(){ $('#filters').innerHTML=['全部',...categories.map(x=>x.name)].map((c,i)=>`<button class="${i?'':'active'}" data-filter="${c}">${c}</button>`).join(''); }
function renderProducts(filter='全部'){const list=filter==='全部'?products:products.filter(p=>p.type===filter);$('#productGrid').innerHTML=list.map(p=>`<article class="product"><div class="product-image" style="background:${p.color}">${p.image?`<img src="${p.image}" alt="${p.name}">`:`<span class="product-icon">${p.icon}</span>`}<span class="product-tag">${p.type}</span></div><h3>${p.name}</h3><p>${p.note}</p><div class="product-bottom"><b>${dollars(p.price)}</b><button class="add" data-id="${p.id}">+</button></div></article>`).join('')||'<p class="no-products">暂时没有商品。</p>';}
function renderCart(){const items=cart.map(i=>({...products.find(p=>p.id===i.id),qty:i.qty})).filter(x=>x.id);const total=items.reduce((s,x)=>s+x.qty,0),subtotal=items.reduce((s,x)=>s+x.qty*x.price,0);$('#cartCount').textContent=total;$('#totalCount').textContent=`${total} 件`;$('#emptyCart').hidden=!!items.length;$('#cartItems').innerHTML=items.map(p=>`<div class="cart-item"><div class="cart-thumb" style="background:${p.color}">${p.image?`<img src="${p.image}" alt="">`:p.icon}</div><div><h3>${p.name}</h3><p>${dollars(p.price)} × ${p.qty}</p></div><div class="quantity"><button data-change="-1" data-id="${p.id}">−</button><b>${p.qty}</b><button data-change="1" data-id="${p.id}">+</button></div></div>`).join('');$('#checkout').disabled=!total;$('#orderSummary').innerHTML=`${items.map(p=>`${p.name} × ${p.qty}`).join('<br>')}<hr><b>商品小计：${dollars(subtotal)}</b>`;}
function applySettings(s){if(!s)return;document.title=`${s.name}｜${s.english}`;$('#brandName').textContent=s.name.replace('的零食屋','');$('#brandEnglish').textContent=s.english;$('#footerName').textContent=s.name;$('#deliveryDescription').textContent=s.delivery;$('#deliveryNote').textContent=`${s.delivery} 我们会电话确认配送安排。`;const c=s.content||{},set=(id,key)=>{if(c[key])$(id).textContent=c[key]};set('#heroEyebrow','heroEyebrow');set('#heroTitle','heroTitle');set('#heroEmphasis','heroEmphasis');set('#heroIntro','heroIntro');set('#heroButton','heroButton');set('#heroCardOneIcon','heroCardOneIcon');set('#heroCardOneText','heroCardOneText');set('#heroCardTwoIcon','heroCardTwoIcon');set('#heroCardTwoText','heroCardTwoText');set('#heroBadgeTop','heroBadgeTop');set('#heroBadgeBottom','heroBadgeBottom');if(c.storyMark){const mark=$('#storyMark');mark.replaceChildren(...Array.from(c.storyMark).flatMap((char,index)=>index?[document.createElement('br'),document.createTextNode(char)]:[document.createTextNode(char)]));}set('#storyEyebrow','storyEyebrow');set('#storyTitle','storyTitle');set('#storySubtitle','storySubtitle');set('#storyText','storyText');set('#storySignature','storySignature');set('#footerHours','footerHours');set('#footerYear','footerYear');}
async function loadShop(){const [p,c,s]=await Promise.all([db.from('products').select('*').eq('is_active',true).order('id'),db.from('categories').select('*').order('id'),db.from('shop_settings').select('*').eq('id',1).maybeSingle()]);if(p.error||c.error||s.error){console.error(p.error||c.error||s.error);return;}products=p.data;categories=c.data;applySettings(s.data);renderFilters();renderProducts();renderCart();}
function toggleCart(show){$('#cart').classList.toggle('open',show);$('#overlay').classList.toggle('visible',show);}
$('#filters').onclick=e=>{if(e.target.dataset.filter){document.querySelectorAll('#filters button').forEach(b=>b.classList.toggle('active',b===e.target));renderProducts(e.target.dataset.filter);}};
$('#productGrid').onclick=e=>{if(e.target.dataset.id){const i=cart.find(x=>x.id===+e.target.dataset.id);i?i.qty++:cart.push({id:+e.target.dataset.id,qty:1});renderCart();}};
$('#cartItems').onclick=e=>{if(e.target.dataset.change){const i=cart.find(x=>x.id===+e.target.dataset.id);i.qty+=+e.target.dataset.change;if(!i.qty)cart=cart.filter(x=>x!==i);renderCart();}};
$('#openCart').onclick=()=>toggleCart(true);$('#closeCart').onclick=()=>toggleCart(false);$('#overlay').onclick=()=>toggleCart(false);$('#checkout').onclick=()=>{toggleCart(false);$('#orderDialog').showModal();};$('#closeDialog').onclick=()=>$('#orderDialog').close();
$('#fulfillment').onchange=e=>{const show=e.target.value==='delivery';$('#addressField').hidden=!show;$('#address').required=show;$('#deliveryNote').hidden=!show;};
$('#orderForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),items=cart.map(x=>({...products.find(p=>p.id===x.id),qty:x.qty})),subtotal=items.reduce((s,x)=>s+x.qty*x.price,0),orderNumber=`TSH-${Date.now().toString().slice(-6)}`;const {error}=await db.from('orders').insert({order_number:orderNumber,customer_name:f.get('name'),phone:f.get('phone'),email:f.get('email')||null,fulfillment:f.get('fulfillment'),address:f.get('address')||null,items,subtotal});if(error){alert('订单暂时无法提交，请稍后重试。');console.error(error);return;}$('#submittedOrderNumber').textContent=orderNumber;$('#orderFormWrap').hidden=true;$('#successMessage').hidden=false;cart=[];renderCart();};
$('#done').onclick=()=>{$('#orderDialog').close();$('#orderForm').reset();$('#orderFormWrap').hidden=false;$('#successMessage').hidden=true;};
function openOrderLookup(){ $('#orderLookupFormWrap').hidden=false;$('#lookupResult').hidden=true;$('#lookupResult').innerHTML='';$('#orderLookupDialog').showModal(); }
$('#openOrderLookup').onclick=e=>{e.preventDefault();openOrderLookup();};$('#closeOrderLookup').onclick=()=>$('#orderLookupDialog').close();
$('#orderLookupForm').onsubmit=async e=>{e.preventDefault();const orderNumber=$('#lookupOrderNumber').value.trim().toUpperCase(),phone=$('#lookupPhone').value.trim(),result=$('#lookupResult');if(!orderNumber&&!phone){result.innerHTML='<p class="dialog-note">请填写订单号或 10 位电话号码。</p>';result.hidden=false;return;}const {data,error}=await db.rpc('lookup_customer_order',{p_order_number:orderNumber,p_phone:phone});if(error||!data?.length){result.innerHTML='<p class="dialog-note">没有找到对应订单；若两项都填写，订单号和电话号码必须属于同一笔订单。</p>';result.hidden=false;return;}result.innerHTML=`<p class="eyebrow">Order Found</p>${data.map(o=>{const items=(o.items||[]).map(i=>`${escapeHtml(i.name)} × ${escapeHtml(i.qty)}`).join('<br>');const request=o.cancellation_requested?'<p class="dialog-note">已提交取消申请，等待店主确认。</p>':o.status==='已取消'?'<p class="dialog-note">该订单已取消。</p>':phone?`<button class="primary-button submit" data-request-cancel="${escapeHtml(o.order_number)}">提交取消申请</button>`:'<p class="dialog-note">如需取消订单，请填写提交订单时的电话号码后再查询。</p>';return `<section><h2>${escapeHtml(o.order_number)}</h2><p class="dialog-note">状态：<b>${escapeHtml(o.status)}</b><br>方式：${o.fulfillment==='delivery'?'配送到家':'到店自取'}${o.address?`<br>地址：${escapeHtml(o.address)}`:''}<br>商品小计：${dollars(o.subtotal)}</p><div class="order-summary">${items}</div>${request}</section>`;}).join('')}`;result.hidden=false;result.querySelectorAll('[data-request-cancel]').forEach(button=>button.onclick=async()=>{button.disabled=true;button.textContent='正在提交申请…';const {data:requested,error:requestError}=await db.rpc('request_order_cancellation',{p_order_number:button.dataset.requestCancel,p_phone:phone});if(requestError){button.disabled=false;button.textContent='提交取消申请';return alert('提交申请时发生错误，请稍后重试。');}if(!requested){button.disabled=false;button.textContent='提交取消申请';return alert('无法提交申请：电话号码与订单不一致，订单已取消，或申请已提交。');}button.closest('section').innerHTML='<p class="eyebrow">Cancellation Requested</p><h2>已提交取消申请</h2><p class="dialog-note">店主确认后，订单会更新为已取消。</p>';});};
db.channel('shop-live').on('postgres_changes',{event:'*',schema:'public',table:'products'},loadShop).on('postgres_changes',{event:'*',schema:'public',table:'categories'},loadShop).on('postgres_changes',{event:'*',schema:'public',table:'shop_settings'},loadShop).subscribe();loadShop();
