-- Ting's Snack House: variants, stock, pricing, delivery, and order lifecycle.
alter table public.products add column if not exists stock integer not null default 100 check (stock >= 0);
alter table public.products add column if not exists is_out_of_stock boolean not null default false;
update public.products set stock = 100 where stock is null;

alter table public.shop_settings add column if not exists delivery_fee numeric(10,2) not null default 5;
alter table public.shop_settings add column if not exists free_delivery_threshold numeric(10,2) not null default 50;
alter table public.shop_settings add column if not exists tax_rate numeric(6,3) not null default 10.5;
alter table public.shop_settings add column if not exists low_stock_threshold integer not null default 5;
update public.shop_settings set delivery_fee=5, free_delivery_threshold=50, tax_rate=10.5, low_stock_threshold=5 where id=1;

create table if not exists public.product_option_groups (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null check (char_length(trim(name)) > 0),
  position integer not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.product_option_values (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.product_option_groups(id) on delete cascade,
  name text not null check (char_length(trim(name)) > 0),
  position integer not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  option_key text not null,
  option_values jsonb not null default '[]'::jsonb,
  price numeric(10,2) not null check (price >= 0),
  stock integer not null default 100 check (stock >= 0),
  is_out_of_stock boolean not null default false,
  image text,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(product_id, option_key)
);
create index if not exists product_option_groups_product_id_idx on public.product_option_groups(product_id, position);
create index if not exists product_option_values_group_id_idx on public.product_option_values(group_id, position);
create index if not exists product_variants_product_id_idx on public.product_variants(product_id, position);

alter table public.orders add column if not exists customer_note text;
alter table public.orders add column if not exists tax_rate numeric(6,3) not null default 10.5;
alter table public.orders add column if not exists tax_amount numeric(10,2) not null default 0;
alter table public.orders add column if not exists delivery_fee numeric(10,2) not null default 0;
alter table public.orders add column if not exists total_amount numeric(10,2) not null default 0;
alter table public.orders add column if not exists archived boolean not null default false;
alter table public.orders add column if not exists archived_at timestamptz;
update public.orders set status='待确认' where status='新订单';
update public.orders set archived=true, archived_at=coalesce(archived_at, now()) where status in ('已取消','已完成');
update public.orders set tax_amount=round(coalesce(subtotal,0)*coalesce(tax_rate,10.5)/100,2), total_amount=round(coalesce(subtotal,0)*(1+coalesce(tax_rate,10.5)/100)+coalesce(delivery_fee,0),2) where total_amount=0;

alter table public.product_option_groups enable row level security;
alter table public.product_option_values enable row level security;
alter table public.product_variants enable row level security;
drop policy if exists "public reads option groups" on public.product_option_groups;
drop policy if exists "public reads option values" on public.product_option_values;
drop policy if exists "public reads variants" on public.product_variants;
drop policy if exists "owner manages option groups" on public.product_option_groups;
drop policy if exists "owner manages option values" on public.product_option_values;
drop policy if exists "owner manages variants" on public.product_variants;
create policy "public reads option groups" on public.product_option_groups for select using (true);
create policy "public reads option values" on public.product_option_values for select using (true);
create policy "public reads variants" on public.product_variants for select using (true);
create policy "owner manages option groups" on public.product_option_groups for all to authenticated using ((auth.jwt() ->> 'email') = 'chenghanchen1@gmail.com') with check ((auth.jwt() ->> 'email') = 'chenghanchen1@gmail.com');
create policy "owner manages option values" on public.product_option_values for all to authenticated using ((auth.jwt() ->> 'email') = 'chenghanchen1@gmail.com') with check ((auth.jwt() ->> 'email') = 'chenghanchen1@gmail.com');
create policy "owner manages variants" on public.product_variants for all to authenticated using ((auth.jwt() ->> 'email') = 'chenghanchen1@gmail.com') with check ((auth.jwt() ->> 'email') = 'chenghanchen1@gmail.com');

create or replace function public.submit_shop_order(
  p_customer_name text, p_phone text, p_email text, p_fulfillment text,
  p_address text, p_note text, p_items jsonb
) returns jsonb language plpgsql security definer set search_path=public as $$
declare
  line jsonb; r record; p record; v record; lines jsonb := '[]'::jsonb;
  item_subtotal numeric(10,2) := 0; fee numeric(10,2); tax numeric(10,2); total numeric(10,2);
  store_tax numeric(6,3); free_at numeric(10,2); base_fee numeric(10,2); num text; order_id uuid;
begin
  if p_phone !~ '^[0-9]{10}$' then raise exception '请输入 10 位数字电话号码'; end if;
  if p_fulfillment not in ('delivery','pickup') then raise exception '取货方式无效'; end if;
  if p_fulfillment='delivery' and coalesce(trim(p_address),'')='' then raise exception '请填写配送地址'; end if;
  if coalesce(char_length(p_note),0)>300 then raise exception '备注不能超过 300 字'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception '购物车为空'; end if;
  select tax_rate, delivery_fee, free_delivery_threshold into store_tax, base_fee, free_at from public.shop_settings where id=1;
  for line in select value from jsonb_array_elements(p_items) loop
    if coalesce((line->>'qty')::integer,0) < 1 then raise exception '商品数量无效'; end if;
    select * into p from public.products where id=(line->>'product_id')::bigint and is_active=true for update;
    if not found then raise exception '商品已下架'; end if;
    if line ? 'variant_id' and nullif(line->>'variant_id','') is not null then
      select * into v from public.product_variants where id=(line->>'variant_id')::bigint and product_id=p.id for update;
      if not found then raise exception '所选规格已不存在'; end if;
      if v.is_out_of_stock or v.stock < (line->>'qty')::integer then raise exception '% 库存不足', p.name; end if;
      update public.product_variants set stock=stock-(line->>'qty')::integer, updated_at=now() where id=v.id;
      lines := lines || jsonb_build_array(jsonb_build_object('product_id',p.id,'variant_id',v.id,'name',p.name,'variant_label',coalesce((select string_agg(x->>'name',' / ') from jsonb_array_elements(v.option_values) x),''),'price',v.price,'qty',(line->>'qty')::integer,'image',coalesce(v.image,p.image),'icon',p.icon));
      item_subtotal := item_subtotal + v.price*(line->>'qty')::integer;
    else
      if p.is_out_of_stock or p.stock < (line->>'qty')::integer then raise exception '% 库存不足', p.name; end if;
      update public.products set stock=stock-(line->>'qty')::integer, updated_at=now() where id=p.id;
      lines := lines || jsonb_build_array(jsonb_build_object('product_id',p.id,'variant_id',null,'name',p.name,'variant_label','','price',p.price,'qty',(line->>'qty')::integer,'image',p.image,'icon',p.icon));
      item_subtotal := item_subtotal + p.price*(line->>'qty')::integer;
    end if;
  end loop;
  fee := case when p_fulfillment='pickup' or item_subtotal >= free_at then 0 else base_fee end;
  tax := round(item_subtotal*store_tax/100,2); total := round(item_subtotal+tax+fee,2);
  num := 'TSH-'||to_char(clock_timestamp(),'YYMMDDHH24MISSMS')||upper(substr(md5(random()::text),1,3));
  insert into public.orders(order_number,customer_name,phone,email,fulfillment,address,customer_note,items,subtotal,tax_rate,tax_amount,delivery_fee,total_amount,status,archived)
  values(num,trim(p_customer_name),p_phone,nullif(trim(p_email),''),p_fulfillment,nullif(trim(p_address),''),nullif(trim(p_note),''),lines,item_subtotal,store_tax,tax,fee,total,'待确认',false) returning id into order_id;
  return jsonb_build_object('id',order_id,'order_number',num,'subtotal',item_subtotal,'tax_rate',store_tax,'tax_amount',tax,'delivery_fee',fee,'total_amount',total);
end $$;

create or replace function public.request_order_cancellation(p_order_number text,p_phone text) returns boolean language plpgsql security definer set search_path=public as $$
declare changed integer;
begin
  update public.orders set cancellation_requested=true,cancellation_requested_at=now()
  where order_number=upper(trim(p_order_number)) and phone=trim(p_phone) and status in ('待确认','已确认') and coalesce(cancellation_requested,false)=false;
  get diagnostics changed=row_count; return changed=1;
end $$;

create or replace function public.lookup_customer_order_v2(p_order_number text,p_phone text) returns setof public.orders language sql security definer set search_path=public as $$
  select * from public.orders where (nullif(trim(p_order_number),'') is null or order_number=upper(trim(p_order_number))) and (nullif(trim(p_phone),'') is null or phone=trim(p_phone)) order by created_at desc;
$$;

create or replace function public.owner_update_order(p_order_id uuid,p_status text,p_fulfillment text,p_delivery_fee numeric) returns jsonb language plpgsql security definer set search_path=public as $$
declare o public.orders%rowtype; line jsonb; fee numeric(10,2); tax numeric(10,2); total numeric(10,2); archived_now boolean;
begin
  if (auth.jwt()->>'email') <> 'chenghanchen1@gmail.com' then raise exception '无权操作'; end if;
  if p_status not in ('待确认','已确认','配送中','已取消','已完成') then raise exception '订单状态无效'; end if;
  select * into o from public.orders where id=p_order_id for update; if not found then raise exception '订单不存在'; end if;
  if p_fulfillment not in ('delivery','pickup') then raise exception '取货方式无效'; end if;
  if p_fulfillment='pickup' and p_status='配送中' then raise exception '自取订单不能设为配送中'; end if;
  fee := case when p_fulfillment='pickup' then 0 else greatest(coalesce(p_delivery_fee,o.delivery_fee),0) end;
  if p_status='已取消' and o.status <> '已取消' then
    for line in select value from jsonb_array_elements(o.items) loop
      if nullif(line->>'variant_id','') is not null then update public.product_variants set stock=stock+coalesce((line->>'qty')::integer,0),updated_at=now() where id=(line->>'variant_id')::bigint;
      else update public.products set stock=stock+coalesce((line->>'qty')::integer,0),updated_at=now() where id=(line->>'product_id')::bigint; end if;
    end loop;
  end if;
  tax := round(o.subtotal*o.tax_rate/100,2); total := round(o.subtotal+tax+fee,2); archived_now := p_status in ('已取消','已完成');
  update public.orders set status=p_status,fulfillment=p_fulfillment,delivery_fee=fee,tax_amount=tax,total_amount=total,archived=archived_now,archived_at=case when archived_now then now() else null end,cancellation_requested=case when p_status='已取消' then false else cancellation_requested end where id=p_order_id;
  return jsonb_build_object('total_amount',total,'archived',archived_now);
end $$;

create or replace function public.owner_reject_cancellation(p_order_id uuid) returns boolean language plpgsql security definer set search_path=public as $$
declare changed integer;
begin
  if (auth.jwt()->>'email') <> 'chenghanchen1@gmail.com' then raise exception '无权操作'; end if;
  update public.orders set cancellation_requested=false,cancellation_requested_at=null where id=p_order_id and cancellation_requested=true and status in ('待确认','已确认');
  get diagnostics changed=row_count; return changed=1;
end $$;

grant execute on function public.submit_shop_order(text,text,text,text,text,text,jsonb) to anon, authenticated;
grant execute on function public.request_order_cancellation(text,text) to anon, authenticated;
grant execute on function public.lookup_customer_order_v2(text,text) to anon, authenticated;
grant execute on function public.owner_update_order(uuid,text,text,numeric) to authenticated;
grant execute on function public.owner_reject_cancellation(uuid) to authenticated;
