import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
const {PGlite}=await import(process.env.TINGS_PGLITE_MODULE||'@electric-sql/pglite');
const source=name=>readFile(new URL('../'+name,import.meta.url),'utf8');
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002',owner='00000000-0000-4000-8000-000000000003';
test('account referrals: completion rewards, guest eligibility, ownership and atomic checkout',async t=>{
  const db=new PGlite();t.after(()=>db.close());
  await db.exec(`
    create role anon;create role authenticated;create role service_role bypassrls;
    create schema auth;
    create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
    create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$;
    create function auth.uid() returns uuid language sql stable as $$ select (auth.jwt()->>'sub')::uuid $$;
    grant usage on schema public,auth to anon,authenticated,service_role;
    insert into auth.users values('${a}','a@example.test',now()),('${b}','b@example.test',now()),('${owner}','chenghanchen1@gmail.com',now());
    create table products(id bigint primary key,name text,price numeric,type text,image text,icon text,is_active boolean default true,is_out_of_stock boolean default false,stock integer default 100,updated_at timestamptz);
    create table product_variants(id bigint primary key,product_id bigint,price numeric,stock integer,is_out_of_stock boolean,option_values jsonb,image text,updated_at timestamptz);
    create table shop_settings(id integer primary key,tax_rate numeric,delivery_fee numeric,free_delivery_threshold numeric,content jsonb);
    insert into products(id,name,price,type) values(1,'Snack',40,'snack');
    insert into shop_settings values(1,0,4,60,'{"storeSettings":{"order":{"minOrder":0},"delivery":{"minDelivery":0}}}');
    create table orders(id uuid primary key default gen_random_uuid(),order_number text,created_at timestamptz default now(),
      customer_name text,phone text,email text,fulfillment text,address text,customer_note text,items jsonb,subtotal numeric,
      tax_rate numeric,tax_amount numeric,delivery_fee numeric,total_amount numeric,status text default '待确认',archived boolean,
      cancellation_requested boolean default false,cancellation_requested_at timestamptz,cancellation_reason text,
      cancellation_stage text,cancellation_rejected_at timestamptz,cancellation_rejected_stage text);
  `);
  for(const file of ['marketing-migration.sql','stacked-offers-referrals-migration.sql','success-referral-rewards-migration.sql','order-submission-protection-migration.sql','customer-accounts-migration.sql','customer-address-v2-migration.sql'])
    await db.exec(await source(file));
  await db.exec("alter table marketing_campaigns add column status text default 'published',add column allow_coupon_stack boolean default true");
  await db.exec(`insert into marketing_coupons(code,name,amount,min_spend,recipient_phone,is_referral_reward) values('REF-LEGACY','Legacy',5,30,'3125550123',true);
    insert into customer_referrals(phone,referral_code) values('3125550123','TSHREF-1234ABCD');`);
  await db.exec(await source('customer-wallet-migration.sql'));
  await db.exec(await source('customer-wallet-migration.sql'));
  const role=async(name,id=null)=>{
    await db.exec('reset role');
    await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify(id?{sub:id,email:id===owner?'chenghanchen1@gmail.com':'customer@example.test'}:{})]);
    await db.exec('set role '+name);
  };
  const scalar=async(sql,args=[])=>Object.values((await db.query(sql,args)).rows[0]||{})[0];
  const wallet=()=>scalar('select get_my_customer_wallet()');
  const submit=(code,user=b,email='guest@example.test',phone='3125550100',key=randomUUID())=>scalar(`select submit_shop_order_account(
    'Customer',$1,$2,'pickup','','','[{"product_id":1,"qty":1}]',$3,$4,null,$5)`,[phone,email,key,user,code]);
  const complete=async(id,status='已完成')=>{await db.exec('reset role');await db.query('update orders set status=$2 where id=$1',[id,status]);};
  const countRewards=async()=>{await db.exec('reset role');return Number(await scalar("select count(*) from marketing_coupons where source='referral'"));};
  await role('authenticated',a);const codeA=(await wallet()).referral_codes[0].code;
  await role('authenticated',b);const codeB=(await wallet()).referral_codes[0].code;
  let placed,reward;
  await t.test('verified accounts have one immutable code; shipping phones claim nothing',async()=>{
    assert.notEqual(codeA,codeB);assert.match(codeA,/^TSHREF-[A-F0-9]{32}$/);
    await role('authenticated',a);
    await scalar("select save_my_customer_details('A','3125550123','')");
    assert.equal((await wallet()).coupons.length,0);
    assert.equal((await wallet()).referral_codes[0].code,codeA);
    assert.equal('phone_masked' in await wallet(),false);
    await db.exec('reset role');
    assert.equal(await scalar("select referrer_user_id from customer_referrals where referral_code='TSHREF-1234ABCD'"),null);
    await assert.rejects(db.query("update customer_referrals set referrer_user_id=$1 where referral_code=$2",[b,codeA]),/不可转让/);
    const d=randomUUID();
    await db.query('insert into auth.users values($1,$2,null)',[d,'new@example.test']);
    assert.equal(Number(await scalar('select count(*) from customer_referrals where referrer_user_id=$1',[d])),0);
    await db.query('update auth.users set email_confirmed_at=now() where id=$1',[d]);
    assert.equal(Number(await scalar('select count(*) from customer_referrals where referrer_user_id=$1',[d])),1);
    await role('anon');await assert.rejects(wallet(),/permission denied/);
  });
  await t.test('self-referrals and legacy phone rewards are denied on the real order path',async()=>{
    await role('service_role');
    await assert.rejects(submit(codeA,a),/不能自荐/);
    await assert.rejects(submit(codeA,null,' A@EXAMPLE.TEST '),/不能自荐/);
    await assert.rejects(submit(codeA,null,''),/游客请填写邮箱/);
    await assert.rejects(submit('TSHREF-1234ABCD'),/无效/);
    await assert.rejects(submit('REF-LEGACY',a,'a@example.test','3125550123'),/不属于此账户/);
  });
  await t.test('authenticated order uses verified email; pending order grants discount but no reward',async()=>{
    await role('service_role');const key=randomUUID();
    placed=await submit(codeA,b,'forged@example.test','3125550100',key);
    assert.equal(Number(placed.discount_amount),5);assert.equal(Number(placed.total_amount),35);
    assert.equal(placed.referral_reward.pending,true);assert.equal(placed.referral_reward.referral_code,codeB);
    assert.equal((await submit(codeA,b,'forged@example.test','3125550100',key)).idempotent_replay,true);
    await assert.rejects(submit(codeA,b,'different@example.test','3125559999'),/重复使用/);
    await assert.rejects(submit(codeA,a,'forged@example.test','3125550100',key),/账户已改变/);
    assert.equal(await countRewards(),0);
    assert.equal(await scalar('select email from orders where id=$1',[placed.id]),'b@example.test');
    assert.equal(Number(await scalar('select count(*) from referral_events')),1);
  });
  await t.test('completion grants exactly one account-owned $5/$30 coupon for 90 days',async()=>{
    await complete(placed.id);
    assert.equal(await countRewards(),1);
    await complete(placed.id,'已配送');await complete(placed.id,'已取货');
    assert.equal(await countRewards(),1);
    reward=(await db.query("select * from marketing_coupons where source='referral'")).rows[0];
    assert.equal(reward.claimed_by_user_id,a);assert.equal(reward.recipient_phone,null);
    assert.equal(Number(reward.amount),5);assert.equal(Number(reward.min_spend),30);
    assert.ok(Math.abs((new Date(reward.ends_at)-new Date(reward.created_at))/86400000-90)<0.01);
    await role('authenticated',a);
    assert.equal((await wallet()).coupons[0].code,reward.code);
    assert.equal((await wallet()).history[0].status,'奖励已发放');
    assert.ok(!JSON.stringify(await wallet()).includes('b@example.test'));
    await role('authenticated',b);assert.equal((await wallet()).coupons.length,0);
    await role('service_role');
    await assert.rejects(submit(reward.code,b),/不属于此账户/);
    await assert.rejects(submit(reward.code,null,'other@example.test'),/不属于此账户/);
    const redeemed=await submit(reward.code,a,'ignored@example.test','7735550188');
    assert.equal(Number(redeemed.discount_amount),5);
    await assert.rejects(submit(reward.code,a,'ignored@example.test','7735550199'),/不属于此账户/);
    await role('authenticated',a);
    assert.equal((await wallet()).coupons[0].uses[0].order_number,redeemed.order_number);
    await scalar("select save_my_customer_details('A','9995550123','')");
    assert.equal((await wallet()).coupons[0].status,'used');
  });
  await t.test('guest is eligible without an account, gains no code; cancellation releases pending eligibility',async()=>{
    await role('service_role');
    const guest=await submit(codeA,null,'guest2@example.test','7735550111');
    assert.equal(guest.referral_reward.referral_code,null);
    await assert.rejects(submit(codeA,null,' GUEST2@EXAMPLE.TEST ','7735550112'),/重复使用/);
    await assert.rejects(submit(codeA,null,'other-guest@example.test','7735550111'),/重复使用/);
    await complete(guest.id,'已取消');
    assert.equal(await countRewards(),1);
    await role('service_role');
    const retry=await submit(codeA,null,'guest2@example.test','7735550111');
    await complete(retry.id,'已完成');
    assert.equal(await countRewards(),2);
    const guestReward=await scalar('select reward_coupon_id from referral_events where referred_order_id=$1',[retry.id]);
    await complete(retry.id,'已取消');
    assert.equal(await scalar('select active from marketing_coupons where id=$1',[guestReward]),false);
    await complete(retry.id,'已完成');
    assert.equal(await countRewards(),2);
    // Registering later generates a code but neither claims guest orders nor resets the benefit.
    const registered=randomUUID();
    await db.query('insert into auth.users values($1,$2,now())',[registered,'guest2@example.test']);
    assert.equal(await scalar('select user_id from orders where id=$1',[retry.id]),null);
    await role('service_role');
    await assert.rejects(submit(codeA,registered,'ignored@example.test','7735550666'),/重复使用/);
  });
  await t.test('previous completed orders block newcomer benefit even without a prior referral',async()=>{
    await role('service_role');
    const existing=await submit(null,null,'existing@example.test','7735550333');
    await complete(existing.id,'已完成');
    await role('service_role');
    await assert.rejects(submit(codeA,null,'EXISTING@example.test','7735550444'),/新客/);
    await assert.rejects(submit(codeA,null,'another@example.test','7735550333'),/新客/);
    await db.exec('reset role');
    await db.exec('update products set price=20 where id=1');
    const before=Number(await scalar('select stock from products where id=1'));
    await role('service_role');await assert.rejects(submit(codeA,null,'small@example.test','7735550888'),/满 \$30/);
    await db.exec('reset role');
    assert.equal(Number(await scalar('select stock from products where id=1')),before);
    await db.exec('update products set price=40 where id=1');
  });
  await t.test('published percentage coupons remain usable; account and endpoint guards hold',async()=>{
    await db.exec('reset role');
    await db.exec("insert into marketing_coupons(code,name,amount,min_spend,total_quantity,discount_kind) values('TENPCT','10 percent',10,30,10,'percent')");
    await role('authenticated',a);
    assert.equal(Number((await scalar("select preview_account_offer('TENPCT','','',40,0)")).discount),4);
    assert.equal((await db.query('select * from referral_events')).rows.length,0);
    await assert.rejects(db.query("update marketing_coupons set claimed_by_user_id=$1",[b]),/permission denied/);
    await assert.rejects(submit(codeB,a),/permission denied/);
    await role('service_role');
    assert.equal(Number((await submit('TENPCT',a)).discount_amount),4);
    await assert.rejects(submit('TENPCT',a,'new@example.test','2125550999'),/不属于此账户/);
    await role('anon');
    assert.equal((await scalar('select preview_account_offer($1,$2,$3,40,0)',[codeA,'a@example.test','2125550011'])).valid,false);
  });
  await t.test('coupon v2: migration preserves old coupons, claims are private/idempotent and capped in real orders',async()=>{
    await db.exec('reset role');
    await db.exec("insert into marketing_coupons(code,name,amount,min_spend,total_quantity,discount_kind) values('OLD50','Old no cap',50,0,100,'percent')");
    await db.exec(await source('coupon-claims-v2-migration.sql'));
    await db.exec(await source('coupon-claims-v2-migration.sql'));
    assert.equal(await scalar("select requires_claim from marketing_coupons where code='OLD50'"),false);
    await assert.rejects(db.exec("insert into marketing_coupons(code,name,amount,discount_kind,claim_valid_days) values('BAD','Missing cap',20,'percent',7)"),/最高减免/);
    const cap=await scalar("insert into marketing_coupons(code,name,amount,discount_kind,max_discount,min_spend,total_quantity,claim_valid_days) values('CAP50','Capped',50,'percent',8,35,2,7) returning id");
    await role('anon');await assert.rejects(scalar('select claim_customer_coupon($1)',[cap]),/permission denied/);
    await role('authenticated',a);
    assert.equal((await wallet()).coupons.find(c=>c.id===cap).status,'claimable');
    assert.equal((await scalar("select preview_account_offer('CAP50','','',40,0)")).valid,false);
    const first=await scalar('select claim_customer_coupon($1)',[cap]);
    assert.equal(first.claimed,true);
    assert.equal((await scalar('select claim_customer_coupon($1)',[cap])).expires_at,first.expires_at);
    assert.equal((await scalar('select claim_customer_coupon($1)',[cap])).already_claimed,true);
    await assert.rejects(db.query('insert into customer_coupon_claims(coupon_id,user_id,expires_at) values($1,$2,now())',[cap,b]),/permission denied/);
    assert.equal(Number((await scalar("select preview_account_offer('CAP50','','',40,0)")).discount),8);
    assert.equal(Number((await scalar("select preview_account_offer('CAP50','','',40,39)")).discount),1);
    assert.equal(Number((await scalar("select preview_account_offer('OLD50','','',40,0)")).discount),20);
    await role('authenticated',b);
    assert.equal(Number(await scalar('select count(*) from customer_coupon_claims')),0);
    await role('service_role');await assert.rejects(submit('CAP50',b,'ignored','7731111111'),/不属于此账户/);
    const capped=await submit('CAP50',a,'ignored','7731111112');
    assert.equal(Number(capped.discount_amount),8);
    await assert.rejects(submit('CAP50',a,'ignored','7731111113'),/不属于此账户/);
    await db.exec('reset role');
    await assert.rejects(db.exec("update marketing_coupons set max_discount=1 where code='CAP50'"),/已有用户领券/);
    const shipping=await scalar("insert into marketing_coupons(code,name,amount,discount_kind,min_spend,total_quantity,claim_valid_days) values('SHIP','Free delivery',0,'free_shipping',35,1,7) returning id");
    await role('authenticated',b);await scalar('select claim_customer_coupon($1)',[shipping]);
    await role('authenticated',a);await assert.rejects(scalar('select claim_customer_coupon($1)',[shipping]),/已领完/);
    await role('authenticated',b);
    assert.equal((await scalar("select preview_account_offer_v2('SHIP','','',40,0,'pickup',false)")).reason,'仅配送订单可用');
    assert.equal((await scalar("select preview_account_offer_v2('SHIP','','',20,0,'delivery',false)")).valid,false);
    assert.equal(Number((await scalar("select preview_account_offer_v2('SHIP','','',40,0,'delivery',false)")).shipping_discount),4);
    await role('service_role');
    await assert.rejects(submit('SHIP',b,'ignored','7732222221'),/仅配送/);
    const shipped=await scalar(`select submit_shop_order_account('B','7732222222','ignored','delivery','Chicago test address','','[{"product_id":1,"qty":1}]',$1,$2,null,'SHIP')`,[randomUUID(),b]);
    assert.equal(Number(shipped.delivery_fee),0);assert.equal(Number(shipped.total_amount),40);
    await db.exec('reset role');
    assert.equal(Number(await scalar('select discount_amount from coupon_redemptions where order_id=$1',[shipped.id])),4);
    assert.equal(Number(await scalar("select (promotion_snapshot->>'coupon_shipping_discount')::numeric from orders where id=$1",[shipped.id])),4);
    const expiring=await scalar("insert into marketing_coupons(code,name,amount,claim_valid_days,total_quantity) values('EXP','Expires',5,1,1) returning id");
    await role('authenticated',a);await scalar('select claim_customer_coupon($1)',[expiring]);
    await db.exec('reset role');await db.query("update customer_coupon_claims set expires_at=now()-interval '1 second' where coupon_id=$1",[expiring]);
    await role('authenticated',a);assert.equal((await wallet()).coupons.find(c=>c.id===expiring).status,'expired');
    assert.equal((await scalar('select claim_customer_coupon($1)',[expiring])).already_claimed,true);
    assert.equal((await scalar("select preview_account_offer('EXP','','',40,0)")).valid,false);
    await role('service_role');
    assert.equal(Number((await submit(null,null,'plain-v2@example.test','7738880010')).total_amount),40);
    const referralAfter=await submit(codeA,null,'referral-v2@example.test','7738880011');
    assert.equal(Number(referralAfter.discount_amount),5);
    const rewardsBefore=await countRewards();await complete(referralAfter.id);
    assert.equal(await countRewards(),rewardsBefore+1);
    const auto=await scalar('select reward_coupon_id from referral_events where referred_order_id=$1',[referralAfter.id]);
    assert.equal(await scalar('select requires_claim from marketing_coupons where id=$1',[auto]),false);
    await role('authenticated',a);
    assert.equal((await wallet()).coupons.find(c=>c.id===auto).status,'available');
    await assert.rejects(scalar('select claim_customer_coupon($1)',[auto]),/无需手动/);
    await role('authenticated',b);await scalar('select claim_customer_coupon($1)',[cap]);
    await role('service_role');assert.equal(Number((await submit('CAP50',b,'ignored','7731111112')).discount_amount),8,'each account has its own use even with the same contact phone');
    await db.exec('reset role');
    const unverified=randomUUID();await db.query('insert into auth.users values($1,$2,null)',[unverified,'unverified-v2@example.test']);
    await role('authenticated',unverified);await assert.rejects(scalar('select claim_customer_coupon($1)',[cap]),/验证邮箱/);
    await db.exec('reset role');
    const feeCoupon=await scalar("insert into marketing_coupons(code,name,amount,discount_kind,min_spend,total_quantity,claim_valid_days) values('FEE-TAX','Shipping tax check',0,'free_shipping',0,1,7) returning id");
    await role('authenticated',a);await scalar('select claim_customer_coupon($1)',[feeCoupon]);
    assert.equal((await scalar("select preview_account_offer_v2('FEE-TAX','','',80,0,'delivery',false)")).valid,false);
    assert.equal((await scalar("select preview_account_offer_v2('FEE-TAX','','',40,0,'delivery',true)")).valid,false);
    await db.exec('reset role');await db.exec('update shop_settings set delivery_fee=0 where id=1');
    await role('authenticated',a);assert.equal((await scalar("select preview_account_offer_v2('FEE-TAX','','',40,0,'delivery',false)")).valid,false);
    await db.exec('reset role');await db.exec('update shop_settings set delivery_fee=4,tax_rate=10 where id=1');
    const campaign=await scalar("insert into marketing_campaigns(name,kind,threshold,amount,allow_coupon_stack) values('No stack','full_reduction',30,5,false) returning id");
    const submitFee=()=>scalar(`select submit_shop_order_account('A','7739990010','ignored','delivery','Chicago','','[{"product_id":1,"qty":1}]',$1,$2,null,'FEE-TAX')`,[randomUUID(),a]);
    await role('service_role');await assert.rejects(submitFee(),/不能|不可/);
    await db.exec('reset role');await db.query('update marketing_campaigns set active=false where id=$1',[campaign]);
    await role('service_role');const feeTax=await submitFee();
    assert.equal(Number(feeTax.delivery_fee),0);assert.equal(Number(feeTax.tax_amount),4);
    assert.equal(Number(feeTax.discount_amount),0);assert.equal(Number(feeTax.total_amount),44,'shipping waiver does not reduce the taxable merchandise amount');
  });
  let shortA,shortB;
  await t.test('short-code migration is idempotent and preserves canonical codes, orders and rewards',async()=>{
    await db.exec('reset role');
    const historyBefore=await scalar('select jsonb_agg(to_jsonb(e) order by id) from referral_events e');
    const ordersBefore=await scalar('select jsonb_agg(to_jsonb(o) order by id) from orders o');
    await db.exec(await source('account-referral-short-codes-migration.sql'));
    shortA=await scalar('select short_code from customer_referrals where referrer_user_id=$1',[a]);
    shortB=await scalar('select short_code from customer_referrals where referrer_user_id=$1',[b]);
    assert.match(shortA,/^[A-HJ-NP-Z2-9]{8}$/);assert.match(shortB,/^[A-HJ-NP-Z2-9]{8}$/);assert.notEqual(shortA,shortB);
    await db.exec(await source('account-referral-short-codes-migration.sql'));
    assert.equal(await scalar('select short_code from customer_referrals where referrer_user_id=$1',[a]),shortA);
    assert.equal(await scalar('select referral_code from customer_referrals where referrer_user_id=$1',[a]),codeA);
    assert.equal(await scalar("select short_code from customer_referrals where referral_code='TSHREF-1234ABCD'"),null);
    assert.deepEqual(await scalar('select jsonb_agg(to_jsonb(e) order by id) from referral_events e'),historyBefore);
    assert.deepEqual(await scalar('select jsonb_agg(to_jsonb(o) order by id) from orders o'),ordersBefore);
    await role('authenticated',a);assert.equal((await wallet()).referral_codes[0].code,shortA);
    await role('authenticated',b);assert.equal((await wallet()).referral_codes[0].code,shortB);
  });
  await t.test('old and short codes share preview, checkout, once-only eligibility and reward ownership',async()=>{
    await role('anon');
    const preview=code=>scalar('select preview_account_offer_v2($1,$2,$3,40,0)',[code,'short-new@example.test','7736660100']);
    assert.deepEqual(await preview(' '+shortA.toLowerCase()+' '),await preview(codeA));
    assert.equal((await preview(shortA)).valid,true);
    assert.equal((await preview('XXXXXXXX')).valid,false);
    await role('service_role');
    const key=randomUUID();
    const shortOrder=await submit(' '+shortA.toLowerCase()+' ',null,'short-new@example.test','7736660100',key);
    assert.equal(Number(shortOrder.discount_amount),5);
    assert.equal((await submit(' '+shortA.toLowerCase()+' ',null,'short-new@example.test','7736660100',key)).idempotent_replay,true);
    await assert.rejects(submit(codeA,null,'short-new@example.test','7736660101'),/重复使用/);
    await assert.rejects(submit(shortA,a),/不能自荐/);
    const oldOrder=await submit(codeA,null,'old-still-valid@example.test','7736660102');
    assert.equal(Number(oldOrder.discount_amount),5);
    const before=await countRewards();
    await complete(shortOrder.id);await complete(oldOrder.id);
    assert.equal(await countRewards(),before+2);
    assert.equal(await scalar('select referrer_user_id from referral_events where referred_order_id=$1',[shortOrder.id]),a);
    assert.equal(await scalar('select referrer_user_id from referral_events where referred_order_id=$1',[oldOrder.id]),a);
    await role('service_role');
    const ownOrder=await submit(null,b,'ignored','7736660103');
    assert.equal(ownOrder.referral_reward.referral_code,shortB);
  });
  await t.test('short codes are private, immutable, unique and cannot shadow coupon codes',async()=>{
    await db.exec('reset role');
    await assert.rejects(db.query('update customer_referrals set short_code=$1 where referrer_user_id=$2',[shortB,a]),/不可转让/);
    await assert.rejects(db.query('update customer_referrals set short_code=null where referrer_user_id=$1',[a]),/不可转让/);
    await assert.rejects(db.query('insert into marketing_coupons(code,name,amount,claim_valid_days) values($1,$2,5,7)',[shortA.toLowerCase(),'Collision']),/重复/);
    await assert.rejects(db.query('insert into customer_referrals(phone,referral_code) values($1,$2)',['7730000001',shortA]),/重复/);
    const newId=randomUUID();await db.query('insert into auth.users values($1,$2,now())',[newId,'short-fresh@example.test']);
    assert.match(await scalar('select short_code from customer_referrals where referrer_user_id=$1',[newId]),/^[A-HJ-NP-Z2-9]{8}$/);
    await db.exec("insert into auth.users select gen_random_uuid(),'bulk-'||n||'@example.test',now() from generate_series(1,100) n");
    assert.equal(await scalar('select count(short_code)=count(distinct short_code) from customer_referrals'),true);
    for(const actor of ['anon','authenticated','service_role']){
      await role(actor,a);
      assert.equal(await scalar("select has_function_privilege(current_user,'public.ensure_account_referral(uuid)','EXECUTE')"),false);
    }
    await role('authenticated',a);
    assert.equal((await wallet()).referral_codes.length,1);
    assert.equal((await db.query('update customer_referrals set short_code=$1 where referrer_user_id=$2 returning id',[shortB,a])).rows.length,0);
    assert.equal((await wallet()).referral_codes[0].code,shortA);
    await role('anon');await assert.rejects(wallet(),/permission denied/);
  });
});
